name: Run tests

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env: 
      URI: ${{secrets.DB_URI}}
      USER: ${{secrets.DB_USER}}
      PASSWORD: ${{secrets.DB_PASSWORD}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.18

      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
